### ISSUE TITLE
Parallel send/recv?

### ISSUE THREAD

**Issue by lzjluzijie** [Visa-Research/coproto#6]
I have code like this

```
  cp::sync_wait(chl.send(d));
  cp::sync_wait(chl.send(e));
  cp::sync_wait(chl.recv(d1));
  cp::sync_wait(chl.recv(e1));
```

and I have a few questions:

1. Can I parallel this operations? I tried to use use `cp::sync_wait(cp::when_all_ready(...))` but it didn't compile. I also tried the `task<>` with `MC_AWAIT` and `co_await` in the tutorial, but still didn't compile. What's the correct way to parallel it?
2. For `LocalAsyncSocket` is there any performance difference between wait/parallel? I think there might be little difference since it's just copying buffer?

**Comment by ladnir** [comment]
Your first option doesn't work due to sync(send(x)) blocking the current thread. 

* Sync means block the thread until the task is completed.
* send(x), create a task that completes once x has been sent and received by the other party.

Hopefully you see the problem. Your recv happens after the send. So it never happens. 

There is a second version of send that can help. send(std::move(x)). This version tells the socket to take ownership of x and send it on my behalf. So this task is completed as soon as it's started. All that I'd done by it is hand x to the internals of the socket. The socket will then send x as soon as it can. So sync(send(std::move(x))) also does not block. 

when_all should work. Can you share the code that doesn't compile? Within a coroutine you'll also need to use the move version. But you can replace sync_wait with co_await/MC_AWAIT. 


Is there a performance difference? Not really for local socket. But there can be a huge difference for protocols over a real network

**Comment by ladnir** [comment]
For the when all, you need to use `cp::sync_wait(cp::when_all_ready(std::move(td0) ,... ))`.

For performance when using local socket, it doesn't matter too much. You can use the move version of send and it will improve a bit most likely.

Are you getting a large overhead? Certainly sending many small messages will not be ideal.

The perform of the libraries could be improved and is on my radar but so far its performance hasn't impacted any of my use cases so haven't invested the time.

**Comment by lzjluzijie** [comment]
Thank you very much, that move works for me. I will provide feedback if I notice any possible improvement.
